const http = require('http');
const fs = require('fs');
const path = require('path');

const ENV_KEYS = [
  'JWT_SECRET', 'TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN', 'TWILIO_PHONE_NUMBER',
  'EVOLUTION_API_BASE_URL', 'EVOLUTION_API_INSTANCE', 'EVOLUTION_API_TOKEN',
  'WHATSAPP_WEBHOOK_TOKEN', 'TELEGRAM_BOT_TOKEN',
  'SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASS', 'FROM_EMAIL', 'FROM_NAME',
  'N8N_BASE_URL', 'VAPID_PUBLIC_KEY', 'VAPID_PRIVATE_KEY',
  'REACT_APP_EMBEDDED_SIGNUP_LAUNCHER_URL',
  'N8N_WEBHOOK_IA_URL', 'N8N_RECOVERY_RESPONSE_WEBHOOK_URL', 'N8N_WEBHOOK_URL_TELEGRAM',
  'N8N_API_KEY', 'N8N_DEFAULT_WORKFLOW_ID', 'MOBIZON_API_KEY', 'MOBIZON_API_DOMAIN',
  'VAPI_API_KEY', 'VAPI_ASSISTANT_ID', 'VAPI_PHONE_NUMBER_ID', 'AUTHENTICATION_API_KEY',
  'EVOLUTION_API_URL', 'EVOLUTION_API_TOKEN',
  'N8N_WEBHOOK_URL_YOUSHOP', 'N8N_RECOVERY_WEBHOOK_URL', 'N8N_EVOLUTION_WEBHOOK_URL',
  'CLOUDFLARE_R2_ACCOUNT_ID', 'CLOUDFLARE_R2_ACCESS_KEY_ID', 'CLOUDFLARE_R2_SECRET_ACCESS_KEY',
  'CLOUDFLARE_R2_BUCKET_NAME', 'CLOUDFLARE_R2_PUBLIC_URL',
  'N8N_PRESCRIPTION_WEBHOOK_URL', 'N8N_CERTIFICATE_WEBHOOK_URL', 'N8N_RECEIPT_WEBHOOK_URL',
  'N8N_REFERRAL_WEBHOOK_URL', 'N8N_BUDGET_WEBHOOK_URL', 'FOCUSNFE_TOKEN', 'FOCUSNFE_ENVIRONMENT',
  'WHATSAPP_INBOX_1_TYPE', 'WHATSAPP_INBOX_1_NAME', 'WHATSAPP_INBOX_1_PROVIDER',
  'WHATSAPP_INBOX_1_INSTANCE_ID', 'WHATSAPP_INBOX_1_N8N_WEBHOOK_URL', 'WHATSAPP_INBOX_1_UNIT_ID',
  'WHATSAPP_INBOX_1_CRM_PIPELINE_NAME',
  'WHATSAPP_INBOX_2_TYPE', 'WHATSAPP_INBOX_2_NAME', 'WHATSAPP_INBOX_2_PROVIDER',
  'WHATSAPP_INBOX_2_INSTANCE_ID', 'WHATSAPP_INBOX_2_N8N_WEBHOOK_URL', 'WHATSAPP_INBOX_2_UNIT_ID',
  'WHATSAPP_INBOX_2_CRM_PIPELINE_NAME',
  'WHATSAPP_INBOX_3_TYPE', 'WHATSAPP_INBOX_3_NAME', 'WHATSAPP_INBOX_3_PROVIDER',
  'WHATSAPP_INBOX_3_INSTANCE_ID', 'WHATSAPP_INBOX_3_N8N_WEBHOOK_URL', 'WHATSAPP_INBOX_3_UNIT_ID',
  'WHATSAPP_INBOX_3_CRM_PIPELINE_NAME',
  'CLINIC_SCHEDULING_AUTOMATION_API_KEY',
  'META_APP_ID', 'META_CONFIG_ID', 'META_APP_SECRET', 'META_SYSTEM_USER_TOKEN',
  'META_REDIRECT_URI', 'EMBEDDED_SIGNUP_ALLOWED_ORIGINS',
  'WEBHOOK_DISPATCHER_BASE_URL', 'WEBHOOK_DISPATCHER_PROVISIONING_SECRET',
  'WHATSAPP_BUSINESS_VERIFY_TOKEN', 'OPENAI_API_KEY',
  'TELECONSULT_JWT_SECRET', 'TELECONSULT_INTERNAL_HOOK_SECRET',
  'TELECONSULT_N8N_TRANSCRIPTION_WEBHOOK_URL', 'TELECONSULT_R2_PUBLIC_URL',
  'XGATE_EMAIL', 'XGATE_PASSWORD',
  'PLATFORM_PLAN_MONTHLY_CENTS', 'PLATFORM_PLAN_DUE_DAY', 'PLATFORM_BILLING_NAME', 'PLATFORM_BILLING_DOCUMENT'
];

function getEnvTokens() {
  const o = {};
  ENV_KEYS.forEach(k => { o[k] = process.env[k] || '__PREENCHER__'; });
  return o;
}

const PORT = parseInt(process.env.PORT || '80', 10);
const htmlPath = path.join(__dirname, 'gerador-easypanel.html');

const server = http.createServer((req, res) => {
  if (req.url === '/env-tokens-exemplo.txt') {
    const p = path.join(__dirname, 'env-tokens-exemplo.txt');
    res.setHeader('Content-Type', 'text/plain');
    fs.createReadStream(p).pipe(res);
    return;
  }
  if (req.url !== '/' && req.url !== '/index.html') {
    res.writeHead(404);
    res.end('Not found');
    return;
  }
  fs.readFile(htmlPath, 'utf8', (err, html) => {
    if (err) {
      res.writeHead(500);
      res.end('Error loading page');
      return;
    }
    const tokens = getEnvTokens();
    const injected = html.replace('__POOH_ENV_JSON__', JSON.stringify(tokens));
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.end(injected);
  });
});

server.listen(PORT, () => {
  console.log('Pooh Deploy listening on port', PORT);
});
